### ISSUE TITLE
Events lasting several days not showing correctly

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/fullcalendar_views#5] opened 2022-02-27 17:39 UTC
I set in a test event stretching over several days. It shows (sort of) correctly for first day, then no show until the day before last day, where it does not show quite correctly. Final day not showing - and end time not showing.

**Comment by indigoxela** [comment] 2022-02-28 06:55
You might struggle with FullCalendar (the library) treating the end as exclusive.

So, if you have an event (without time), that has the start set to for example February 28th, and the end to March 3rd, FC displays Feb. 28th to March 2nd.

Can you provide the raw dates to verify?

**Comment by Egmund** [comment] 2022-02-28 07:50
I have start 1.3.22 at 14.12 to 8.3.22 at 17.14
 - so it is with time
 
The date-repeat 'thing look like this:
sesshin test

    03/01/2022 - 2:12pm – 03/08/2022 - 5:14pm

**Comment by indigoxela** [comment] 2022-02-28 07:57
Hm, not sure what you see as problem....

Dates with times (even if the event spans over several days) get displayed correctly here.

Can you provide a screenshot + dates + an explanation, what you would have expected to display?

**Comment by Egmund** [comment] 2022-02-28 08:02
I set the site temporarily out of maintenance mode, so you can inspect:
https://medlemmer.havredal.org/kalender
I expect the whole range of dates to show the event (blue w. white text)

**Comment by indigoxela** [comment] 2022-02-28 08:04
> I expect the whole range of dates to show the event

Mind to explain? I currently completely fail to understand, what you're after. :smirk:

**Comment by Egmund** [comment] 2022-02-28 08:06
On this site - the actual live one w. 'old' fullcalendar. there is a blie line for all dates - month of May.
https://bdrop.buddhistisksamfund.dk/kalender
This is what I expect, so people can see the length of the events.

**Comment by indigoxela** [comment] 2022-02-28 08:08
No, wait, got it. The event appears to be "cut off", but that looks like a style bug (theme?). Maybe I can figure out.

**Comment by Egmund** [comment] 2022-02-28 08:10
Ah yes it is. In Basis it looks just fine.

**Comment by Egmund** [comment] 2022-02-28 08:12
I need to 'debug' here, because The 'bdrop' site also use Axioma without problems.
But of course different version of fullcalendar

**Comment by Egmund** [comment] 2022-02-28 08:22
Just killed my 'bdrop' site by installing fullcalendar-views and resource-timeslot:
Call to a member function get_option() on null
Will have to backtrack

**Comment by Egmund** [comment] 2022-02-28 08:44
Restored from yesterday's backup. Database was somehow messed up. All well again

**Comment by Egmund** [comment] 2022-02-28 09:01
If Axioma is the problem, then I can use Bootstrap Lite.

**Comment by indigoxela** [comment] 2022-02-28 09:03
> If Axioma is the problem, then I can use Bootstrap Lite.

I think, it's important to _identify_ the problem. There might be some possible solution in the module. If one theme messes things, another one might also, and that's not what we want.

**Comment by indigoxela** [comment] 2022-02-28 09:26
Identified: Axioma does some overflow: hidden with td. Fixed in latest commit.

**Comment by Egmund** [comment] 2022-02-28 09:46
Super. I will update

**Comment by Egmund** [comment] 2022-02-28 09:54
Worked AFTER I copied the css bit to an Axioma css.
Should it not be loaded by the fullcalendat-views?

**Comment by indigoxela** [comment] 2022-02-28 10:02
> Worked AFTER I copied the css bit to an Axioma css.

Nope, hacking Axioma shouldn't be necessary.

Can you verify, that this code is in place in your install: https://github.com/backdrop-contrib/fullcalendar_views/blob/8535e23e81505f3781c4dc620b9a38299996b292/css/fullcalendar-views.css#L17

And did you flush caches?

**Comment by Egmund** [comment] 2022-02-28 10:27
Yes, that was in place. And cache was flushed.
But I did not un-install and re-install the module though, just uploading the new code.

**Comment by indigoxela** [comment] 2022-03-03 13:53
I'm assuming that you were able to fix the problem, and the module now also fixes possible truncation caused by theme css.

If not, feel free to reopen this issue. And many thanks for all your testing!

**Closed as completed by indigoxela** 2022-03-03 13:53 UTC

**Comment by Egmund** [comment] 2022-03-03 14:45
All fine here. The problem was my site using an old renamed version - now deleted.
