### ISSUE TITLE
Repeat date not repeating

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/fullcalendar_views#1] opened 2022-02-26 05:19 UTC
Several problems:
Repeat date is not repeating. I only get the first date (set to repeat weekly for one year).
Display is 'merely' an <a href=" etc. Not a proper text.
Text is not clickable.

In 'Fields' I have: Title, Date (which is a repeat-date field) and Body

What am I missing / messing up?

**Comment by Egmund** [comment] 2022-02-26 05:56
Here are some lines from log-report:
Notice: Trying to access array offset on value of type null i FullcalendarViewsStyleCalendar->options_form() (linje 71 af /home/haurdalnet/medlemmer.havredal.org/modules/fullcalendar_views-1.x-1.x/views/fullcalendar_views_style_calendar.inc).

Same for line 49, 57, 64

**Comment by Egmund** [comment] 2022-02-26 07:00
I am getting somewhere:
Got the proper title - but it is not clickable, so content not showing.
Got it to repeat. Two things needed to be changed. The field need to be set to 'unlimited' in content type. The date field in view need to have un-checked 'show all values on same line'

**Comment by indigoxela** [comment] 2022-02-26 09:46
I guess, you already figured out some things...

> Repeat date is not repeating...

As the [README](https://backdropcms.org/project/repeating_dates) of that module already states:

> The field cardinality global setting controls the max amount of date values, that get saved to the database. Make sure that this value is high enough.

In addition to the documentation, you get a message presented on node form, if the values are set too low:

"The "Number of values" setting in the field Dates is very low. You can only save 1 value."

I wouldn't know what else to do to prevent wrong configuration.

> Got the proper title - but it is not clickable, so content not showing.

I don't understand that. The title itself is not supposed to contain markup (see the help text). The url gets wrapped around the complete event (by Fullcalendar).

> Notice: Trying to access array offset on value of type null i FullcalendarViewsStyleCalendar->options_form() 

That's interesting. Can you provide the steps to reproduce, please? I'll try to dig myself, though.

**Comment by indigoxela** [comment] 2022-02-26 10:25
I found the cause for the notices - should be fixed now in latest commit.

**Comment by Egmund** [comment] 2022-02-26 10:45
Thank you for all your time with this.
The thing about non-clickable is unclear to me (getting old). Is it possible to turn the event shown (title) into a link as in the 'fullcalendar' module? Am I overlooking something?

**Comment by Egmund** [comment] 2022-02-26 10:47
The notices are gone now since changing the aforementioned things. So I guess it was improper setup here.

**Comment by indigoxela** [comment] 2022-02-26 11:35
> The thing about non-clickable is unclear to me

If you want to make the event clickable (a link), you only have to set the "URL" to a path field. "Content: Path" is probably what you're after (if I don't misunderstand completely :wink:)

> The notices are gone now since changing the aforementioned things...

That was actually a bug, which only pops up initially - when the display has no settings yet. That bug got fixed in the latest commit.

**Comment by Egmund** [comment] 2022-02-26 13:02
Thank you for pointing me in the right direction. I now got the proper links - via "Content: Path".
This module now seems a better replacement for "Fullcalendar" on my 'live' site - or?

**Comment by indigoxela** [comment] 2022-02-26 13:18
> This module now seems a better replacement for "Fullcalendar" on my 'live' site

It's still in an early stage (this code came to life only yesterday!), so I really recommend to wait a little longer. I don't assume, it's ready for production.
You already pointed me to a bug (OK, fixed now), who knows what else still needs to get fixed. :stuck_out_tongue_winking_eye:

And also: the code still contains a bunch of `@todo` comments, which need to get addressed before a release can go out.

But you could help me by sharing some ideas about what additional settings might make sense. Fullcalendar (legacy) has a lot more options, but I don't know which ones really make sense.

**Comment by Egmund** [comment] 2022-02-26 13:23
I will compare this with Fullcalendar - and the Drupal 7 calendar - to see what would make sense to me.
Thank you again for this work and all your help.

**Comment by indigoxela** [comment] 2022-02-26 15:57
Just ran into the same problem when testing... dates weren't repeating because of the group_rows setting.

That's really a trip hazard, I added a warning message in views previews. :wink:

**Closed as completed by indigoxela** 2022-02-26 15:57 UTC
