### ISSUE TITLE
Installing kills my site

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/fullcalendar_views#7] opened 2022-03-03 16:10 UTC
After (attempt to) install I get:
Call to a member function get_option() on null
and site is dead.
There must be a conflict with something. Fullcalendar - the 'old' one?
I will investigate further, but for now I will restore my site from backup.

This is not my test site, but a live one unfortunately.

**Comment by Egmund** [comment] 2022-03-03 17:42
I cloned the site, uninstalled (old) fullcalendar, installed the new fullcalendar-views (& dependencies).
Now fine. Conflict w. the 'old' FC

**Comment by indigoxela** [comment] 2022-03-04 06:54
Ooops, right, I could confirm that.

But I don't understand what happens.

The problem arises in this function of fullcalendar (legacy):
```
function fullcalendar_views_query_alter(&$view, &$query) {
  if ($view->display_handler->get_option('style_plugin') != 'fullcalendar') {
    return;
  }

  $query->distinct = TRUE;
}
```
A quick trick to get the site working again is to insert a `return;` right at the beginning of that function. Then uninstalling is possible.

No clue, why display_handler is NULL at that point.

**Comment by indigoxela** [comment] 2022-03-04 07:00
And there's also:
```
Warning: Creating default object from empty value in fullcalendar_views_query_alter() (.../modules/fullcalendar/includes/views/fullcalendar.views.inc).
```
@laryn any clue, what's going on there?

The style plugins have different names, so that can't be the cause.

**Comment by indigoxela** [comment] 2022-03-04 07:08
OMG...

Fullcalendar legacy implements hook_views_query_alter.

Now a module fullcalendar_views exists, so this hook gets interpreted as hook_query_alter, which is a complete different one.

$view doesn't exist there.

I might be necessary to completely rename this module here, to prevent further conflicts.

On the other hand, fullcalendar legacy could catch all problems with a little isset(). I'll try that, too.

**Comment by Egmund** [comment] 2022-03-04 09:37
We do, though, not need both.
Quick & dirty: A warning before install this module to remove the 'legacy'/'old' module.
Better : This module's install will check for 'legacy' and either remove that or - at least - stop installing with a warning to uninstall 'legacy' (old) module.

**Comment by indigoxela** [comment] 2022-03-04 09:44
> A warning before install this module to remove the 'legacy'/'old' module.

I wouldn't know how. The module isn't installed yet, so it can't execute any code, also no warnings.

> This module's install will check for 'legacy' and either remove that or - at least - stop installing

Too late. The site seems to break immediately when trying to install fullcalendar_views, already in the "confirm" step. Not sure if it's possible to catch anything in that step.

So I'm waiting for some feedback by @laryn, if he wants to do a `isset` to catch the problem in the legacy module. Otherwise we really might have to rename this module.

**Comment by Egmund** [comment] 2022-03-04 10:23
A warning in the 'readme'?

**Comment by indigoxela** [comment] 2022-03-04 11:29
> A warning in the 'readme'?

Sure, that's the first step: https://github.com/backdrop-contrib/fullcalendar_views#known-issues

**Comment by indigoxela** [comment] 2022-03-04 15:05
@laryn is our hero - he merged the isset() PR!

**Comment by laryn** [comment] 2022-03-04 15:13
I also renamed the other one (not the namespace but the label): `FullCalendar (Legacy version)` and included this in the README:

> NOTE: For a more recent version of FullCalendar and support for a wider range of date fields, you may wish to look into the more recent [FullCalendar Views](https://github.com/backdrop-contrib/fullcalendar_views) module.

**Comment by Egmund** [comment] 2022-03-04 15:15
Very good

**Closed as completed** 2022-03-16 09:59 UTC
